openapi: 3.0.1
info:
  title: SampleHello
  description: API Definition of SampleHello
  version: 1.0.0
servers:
- url: http://localhost:8290/samplehello
paths:
  /hi:
    get:
      responses:
        default:
          description: Default response
