openapi: 3.0.1
info:
  title: Send
  description: API Definition of Send
  version: 1.0.0
servers:
- url: http://localhost:8290/send-config
paths:
  /:
    get:
      responses:
        default:
          description: Default response
